SERVER: Getting webdriver...


------------------------------------------
+++ Guardando documento 'CO57011974' nuevo en la BD...
------------------------------------------
+++ DEBUG: formFields '{'id': '1953', 'numero': 'CO57011974', 'txt0a': 'CO', 'txt00': 'CO57011974', 'txt01': '', 'txt02': 'CLARIOS ANDINA S.A.S.\nNIT. 900388600\nCAR 35 No. 10-300 ACOPI\nYUMBO COLOMBIA\n\n', 'txt03': 'DISTRIVEHIC DISTRIBUIDORA DE VEHICULOS S.A.S\nRUC 1792365031001\nAV. DE LOS GRANADOS E11-67 Y DE LAS HIEDRAS   \nQUITO ECUADOR\n', 'txt04': 'DISTRIVEHIC DISTRIBUIDORA DE VEHICULOS S.A.S\nRUC 1792365031001\nAV. DE LOS GRANADOS E11-67 Y DE LAS HIEDRAS   \nQUITO ECUADOR\n', 'txt05': 'DISTRIVEHIC DISTRIBUIDORA DE VEHICULOS S.A.S\nRUC 1792365031001\nAV. DE LOS GRANADOS E11-67 Y DE LAS HIEDRAS   \nQUITO ECUADOR\n', 'txt06': 'IPIALES COLOMBIA , 02 DE ENERO DE 2024', 'txt07': 'IPIALES COLOMBIA , 02 DE ENERO DE 2024', 'txt08': 'QUITO ECUADOR', 'txt09': 'DIRECTO // CREDITO', 'txt10': '20 PALLETS', 'txt11': '', 'txt12': 'BATERIA AUTOMOTRIZ PLOMO 12V \nLBN2 700 BATERIA AUTOMOTRIZ PLOMO 12V \nLBN2 800 BATERIA AUTOMOTRIZ PLOMO 12V \nLBN3 900 BATERIA AUTOMOTRIZ DE PLOMO 12 \n34PMV 850 BATERIA AUTOMOTRIZ PLOMO 12V \n34PMV 850 BATERIA AUTOMOTRIZ PLOMO 12V \nLBN2 BATERIA AUTOMOTRIZ PLOMO 12V \nBATERIA AUTOMOTRIZ DE PLOMO 12\n24800 BATERIA AUTOMOTRIZ PLOMO 12V \nBTS 35 750 (35-11)CDENERGIZER ECU \nSELL BATERIA AUTOMOTRIZ DE PLOMO 12 VOLTIOS \nBATERIA AUTOMOTRIZ DE PLOMO 12 VOLTIOS\n\n', 'txt13_1': '18089.00', 'txt13_2': '18731.00', 'txt14': '', 'txt15': '', 'txt16': 'FCA IPIALES\nUSD 68933.84', 'txt17_11': '', 'txt17_12': '', 'txt17_13': '', 'txt17_14': '', 'txt17_21': '', 'txt17_22': '', 'txt17_23': '', 'txt17_24': '', 'txt17_31': '550.00', 'txt17_32': '', 'txt17_33': '', 'txt17_34': '550.00', 'txt17_41': 'USD', 'txt17_42': '', 'txt17_43': '', 'txt17_44': 'USD', 'txt18': 'FACTURAS NÂ° FXCL000019802', 'txt19': 'IPIALES COLOMBIA , 02 DE ENERO DE 2024', 'txt21': 'INGRESA A BODEGAS ALMAROS', 'txt22': 'MRN CEC202420230500\n', 'txt24': '', 'fecha_creacion': '2024-09-17', 'referencia': 'CLARIOS'}'
SERVER: Traceback (most recent call last):
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(200)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lg/BIO/iaprojects/ecuapassdocs/EcuapassDocs/EcuapassDocs2-dev/dev/migration/./bot_migration.py", line 48, in main
    saveDocs (inputDir)
  File "/home/lg/BIO/iaprojects/ecuapassdocs/EcuapassDocs/EcuapassDocs2-dev/dev/migration/./bot_migration.py", line 56, in saveDocs
    bot.saveDocFilesToDB (inputDir)
  File "/home/lg/BIO/iaprojects/ecuapassdocs/EcuapassDocs/EcuapassDocs2-dev/dev/migration/./bot_migration.py", line 372, in saveDocFilesToDB
    self.saveNewDocToDB (formFields, self.docType, self.pais, usuario)
  File "/home/lg/BIO/iaprojects/ecuapassdocs/EcuapassDocs/EcuapassDocs2-dev/dev/migration/./bot_migration.py", line 408, in saveNewDocToDB
    formModel.save ()
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1036, in _save_table
    updated = self._do_update(
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1101, in _do_update
    return filtered._update(values) > 0
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1276, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lg/BIO/iaprojects/ecuapassdocs/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(200)


